# Generated by Django 2.1.3 on 2018-11-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caballero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('puto', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
